### ISSUE TITLE
API fails to start

### ISSUE THREAD

**Issue by pooleja** [blockstack/stacks-local-dev#14]
Just tried bringing up the default config and the api is failing with the following error:

```
> @blockstack/stacks-blockchain-api@1.0.0 start /app
> node ./lib/index.js

{"message":"Event observer listening at: http://0.0.0.0:3700","level":"info","timestamp":"2021-02-10T20:25:38.525Z"}
{"level":"error","message":"The configured STACKS_CHAIN_ID does not match the node's: 1 vs 2147483648 The configured STACKS_CHAIN_ID does not match the node's: 1 vs 2147483648","stack":"Error: The configured STACKS_CHAIN_ID does not match the node's: 1 vs 2147483648\n    at init (/app/lib/index.js:71:23)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2021-02-10T20:25:38.554Z"}
{"level":"error","message":"app failed to start: Error: The configured STACKS_CHAIN_ID does not match the node's: 1 vs 2147483648 The configured STACKS_CHAIN_ID does not match the node's: 1 vs 2147483648","stack":"Error: The configured STACKS_CHAIN_ID does not match the node's: 1 vs 2147483648\n    at init (/app/lib/index.js:71:23)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2021-02-10T20:25:38.555Z"}
npm ERR
```

**Comment by wileyj** [comment]
hmm, seems like some new ENV VARS have been added to the API. thanks, I'll make some updates

**Comment by wileyj** [comment]
I'm moving the branches around a bit, soon `master` will be setup for mainnet and the changes have been added already. 
mainnet  branch is here: https://github.com/blockstack/stacks-local-dev/tree/mainnet

if you were seeing this error for mocknet, i.e. a container named `mocknet_stacks-node-api`, that's been updated in a new branch here: https://github.com/blockstack/stacks-local-dev/tree/mocknet

**Comment by pooleja** [comment]
OK, yeah I can confirm the error is not present on the mocknet branch.  Thanks.

**Comment by wileyj** [comment]
Made a few more updates for other issues around mocknet:
https://github.com/blockstack/stacks-local-dev/pull/17
https://github.com/blockstack/stacks-local-dev/pull/15
https://github.com/blockstack/stacks-local-dev/pull/12
https://github.com/blockstack/stacks-local-dev/pull/10
