### ISSUE TITLE
Check BTC balance

### ISSUE THREAD

**Issue by iamgenchi** [blockstack/stacks-local-dev#22]
Hi Team, 

I understand by default, the bitcoin node is "bitcoind.blockstack.org".

How can one check the BTC balance on the mocknet for a particular account?

**Comment by wileyj** [comment]
For mocknet, this is no longer the case - you're welcome to use a customized miner config to use any bitcoin config node you want though.  

https://github.com/blockstack/stacks-local-dev/blob/mocknet/stacks-node-miner/Config.toml.template#L9-L12

Generically, to check a wallet address it's easier to use a public service if you have an address on btc mainnet or testnet. 
i.e.. `https://www.blockchain.com/btc/address/1Eu4YpsG7qZciim44pP36GwxToqxaoq9xb`

For regtest, you'd have to do a little more work with the bitcoin-cli to get the data you're looking for.

**Comment by iamgenchi** [comment]
Thank you @wileyj 

> For mocknet, this is no longer the case

That’s interesting.. so, by default, what Bitcoin running instance is being used with the mocknet? Is it a local instance?
