### ISSUE TITLE
.env checked into source control

### ISSUE THREAD

**Issue by MarvinJanssen** [blockstack/stacks-local-dev#24]
It seems dangerous to check `.env` into source control. I suggest creating a `sample.env` file and unchecking `.env`. The file us usually reserved for environment specific information and my contain sensitive data. `setup.sh` checks for the existence of the file anyway, and it could even copy `sample.env` if no custom `.env` exists.

**Comment by wileyj** [comment]
https://github.com/blockstack/stacks-local-dev/commit/59f2d40a555f23085e0f19f437a64c61de4fcc88
