### ISSUE TITLE
For mocknet, use same private keys as in stacks-blockchain

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-local-dev#41]
To streamline development, it would be nice to use the same private key between mocknet and stacks-local-dev

https://github.com/blockstack/stacks-blockchain/blob/master/testnet/stacks-node/conf/mocknet-follower-conf.toml

**Comment by wileyj** [comment]
https://github.com/blockstack/stacks-local-dev/blob/master/configurations/mocknet/Config.toml.sample

are the private keys here incorrect?
