### ISSUE TITLE
Mocknet txn shows error : \"error\":\"transaction rejected\",\"reason\":\"NotEnoughFunds\"

### ISSUE THREAD

**Issue by Akirtovskis** [blockstack/stacks-local-dev#42]
I might be missing something obvious, but setting up local mocknet environment is not really working for me. 

Steps I run : 

 - `./manage.sh mocknet pull`
 - `./manage.sh mocknet up`
 - `stx make_keychain -t | jq . > cli_keychain.json`
 - ```curl -s -X POST "localhost:3999/extended/v1/faucets/stx?address=$(cat ./cli_keychain.json | jq -r .keyInfo.address)" | jq.```
 
Console output from this one is : 
<img width="1664" alt="Screenshot 2021-06-07 at 21 45 46" src="https://user-images.githubusercontent.com/25903618/121078868-be54ef00-c7d9-11eb-87b0-9bf13244ec1b.png">

The output of `./manage.sh mocknet logs` :
<img width="1677" alt="Screenshot 2021-06-07 at 21 46 36" src="https://user-images.githubusercontent.com/25903618/121078999-e5132580-c7d9-11eb-9300-e5c4db3d1cc6.png">

**Comment by wileyj** [comment]
I'll have to confirm this, but i think this is the wrong invocation since this is mocknet: `stx make_keychain -t`, where `-t` is testnet. 

i'll check our current docs and get back to you on this - if you don't mind, could you link me to where you saw this command?

**Comment by Akirtovskis** [comment]
@wileyj from [here](https://github.com/blockstack/stacks-local-dev#deploying-a-contract) . I guess it makes sense that it is not working like this as these are docs for `private-testnet`, but in that case, would be nice to see more details for mocknet setup.

**Comment by nurASingh** [comment]
Do we have any update on this ? I am still struggling with making mocknet working.

Documentation mentioned above is extremely poor.

**Comment by wileyj** [comment]
Where are you struggling in regards to mocknet, and which docs in particular are you having an issue with?
