### ISSUE TITLE
Bitcoin faucet

### ISSUE THREAD

**Issue by dorucioclea** [blockstack/stacks-local-dev#45]
Hey guys

Do you know how could I secure test bitcoins from the faucet in a private-testnet setup?

Can I do something like this? https://github.com/blockstack/gh-action-testing/blob/7fb382a5e21f197cda6888231044dc63d1af295c/net-test/etc/bitcoin-neon-controller.toml.in

Thank you

**Comment by wileyj** [comment]
not quite. that's for a regtest - you'll either need to get some sent to an address you own, or use a public faucet:
https://duckduckgo.com/?q=bitcoin+testnet+faucet&atb=v230-1&ia=web

**Comment by dorucioclea** [comment]
Is there any programmatic way to do this in mocknet? I'm interested in this for some integration tests

**Comment by wileyj** [comment]
https://blockstack.github.io/stacks-blockchain-api/#tag/Faucets

https://github.com/blockstack/stacks-blockchain/blob/master/testnet/puppet-chain/config.toml.default

should be what you're looking for here. if you're using the private-testnet network, take a look at this config: https://github.com/blockstack/stacks-local-dev/blob/master/configurations/private-testnet/puppet-chain.toml.sample

**Comment by dorucioclea** [comment]
Thank you very much, I'll close this issue 👌
