### ISSUE TITLE
Documentation: How to recover from error "db entry missing for parent block.."

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-local-dev#52]
Now and then, I get an error "DB entry missing for parent block..."
There should be a documentation how to recover from this error and other failures.

**Comment by wileyj** [comment]
Unfortunately, I'm not aware of any way to recover from an error like that - it means the blockchain and the API are out of sync. 

Nonetheless, it should be documented

**Comment by wileyj** [comment]
https://github.com/blockstack/stacks-local-dev/commit/02aa39fb941d64ac937515b07ba3b3efaa122425
